version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 10.0

  build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore
      - echo Publishing app...
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo Zipping published output...
      - cd publish && zip -r ../app.zip . && cd ..
      - echo Uploading to S3...
      - aws s3 cp app.zip s3://yanitsharma-crud-app-builds/builds/app-$CODEBUILD_BUILD_NUMBER.zip
      - aws s3 cp app.zip s3://yanitsharma-crud-app-builds/builds/latest.zip

artifacts:
  files:
    - app.zip